<h1 class="ribbon shadow"><span class="ribbon_shadow"></span>Les règles du Paintball</h1>
<p>Le <b>paintball</b> est une activité sportive opposant deux équipes dont les joueurs sont équipés de masques de protection et de lanceurs (ou marqueurs). Les lanceurs propulsent par air comprimé ou par CO<sub>2</sub> des billes de peinture de calibre 0.68 ou de 0.50 et de 0.43 et de 0.40.</p>

<p>Dans sa version sportive, deux équipes de 7;5 ou 3 joueurs s'opposent pour récupérer un drapeau situé dans la base adverse afin de le ramener à sa base dans un temps limité. Un joueur est éliminé quand il est touché par une bille.</p>
<p>Ce sport peut être dangereux s'il est mal encadré ou si les conditions de sécurité ne sont pas respectées (zone de jeu clairement délimitée par des filets, port d'un masque spécifique, lanceur en bon état et plafonné à une certaine vitesse, bouchon de canon mis en permanence hors des terrains, etc.)</p>
<p>Le paintball est différent de l'Airsoft qui se pratique avec des répliques d'armes et des billes de plus petit calibre (<span class="nowrap">6&#160;mm</span>) dures en plastique ou, comme c'est de plus en plus le cas, en une matière biodégradable.</p>

<p>Les premiers lanceurs furent utilisés par les éleveurs australiens pour marquer le bétail dans les années 1970. En effet la taille des ranchs et la méthode d'élevage des troupeaux qui paissent dans la nature, obligent alors les éleveurs à travailler comme des cowboys des temps modernes. En motos, en quads et en hélicoptères, ils rassemblent les troupeaux et comme le cas se présente souvent les animaux peuvent se regrouper avec ceux d'autres ranchs. Il fallait donc trouver, avant d'embarquer les animaux, un moyen simple pour marquer la propriété, qui soit visible sur le moment grâce aux marquages au fer rouge. En réalité, le paintball est né de l'isolement de ces ranchs, qui peuvent couvrir des centaines de km² et qui ne sont accessibles que par 4×4 ou par avion. La population est principalement masculine et les lanceurs hypodermiques furent alors utilisés pour s'amuser entre cowboys… Ce sont des choses qui arrivent et parallèlement à ceci les gérants des exploitations purent remarquer une baisse des bagarres au sein de leurs hommes. À la fin des années 1970, des tournois opposaient alors des ranchs voisins afin de faire décompresser les hommes puis la Nouvelle-Zélande fut «&#160;touchée&#160;», avant d'arriver aux États-Unis, où les lanceurs pour marquer le bétail furent exportés en 1979.</p>
<p>Sous forme de jeu à proprement parler comme on le connaît aujourd'hui, il s'est tout d'abord développé aux États-Unis. Le premier tournoi a été organisé le 27 juin 1981. Il est alors connu sous le nom de <i>National Survival Game</i> aux États-Unis d'Amérique, et <i>Skirmish Games</i> en Australie, mais y est dès 1984 désigné sous le nom de <i>paintball</i> par les fabricants dans les boutiques de jeux et sport, et parfois même dans les supermarchés.</p>

<p>Cette activité est arrivée en Grande-Bretagne à la fin des années 1980 puis en France et dans le reste de l'Europe au début des années 1990, sous l'influence entre autres de séminaires de motivation d'entreprise ou de jeu de rôle grandeur nature.</p>
<p>Le jeu se révèle extraordinairement tactique et est un excellent sport d'équipe très riche en interactions et en sensations. Il présente par ailleurs l'avantage d'être très complet en demandant un large panel de compétences.</p>

<p>«&#160;La simulation militaire au Paintball est devenue tellement populaire que plusieurs sites à travers le monde offrent une multitude de programmes d’entraînement. Certains sites le font avec peu d’équipement ou de façon très amateur. Certains centres sont dans un monde à part&#160;; la formation T.E.A.M. disponible chez Bigfoot Paintball le fait de manière à ce que l’immersion soit complète dans un environnement d’actions intenses sur une base quotidienne.&#160;»</p>
<ul>
<li>[Jungle] mai 2008*</li>
</ul>
<p>Les clubs français se sont organisés en «&#160;fédération&#160;» en 1996 pour promouvoir une vision plus sportive du paintball, sous le nom de Fédération de Paintball Sportif. En 2006, elle comprenait 24&#160;000 licenciés et regroupait 212 clubs affiliés dans 22 ligues. Des tournois régionaux, nationaux et internationaux sont organisés. Aujourd'hui le paintball est officiellement représenté dans près de quarante pays sur tous les continents. Des championnats internationaux ont lieu tous les ans pour des matchs par équipes de 5 et 7 joueurs. Ils regroupent entre 50 et 200 équipes à chaque fois, deux manches ont lieu en France&#160;: la World Cup à Toulouse et le Disney French Open au Parc Disneyland dans le cadre du circuit privé Millennium.</p>

<p>Au Québec le sport tel qu’on le connaît aujourd’hui a commencé à se développer au début des années 1990. Certains centres en Estrie et dans les Laurentides ont commencé à ouvrir, offrant au nombre grandissant de joueurs l’opportunité de jouer sur des terrains aménagés à cet effet. Au début, c’était surtout des terrains naturels avec des barricades de bois, des piles de pneus ou de barils, bref des installations assez simples. En 1995, Paintball Mirabel a ouvert ses portes à St Alphonse –Rodriguez dans Lanaudière. Après quelques années seulement, ce centre devint le plus important au Québec, au Canada et dans le monde entier. «&#160;Au Québec, dans l’une des plus belles provinces du Canada se trouve l’un des plus spectaculaires terrains au monde. Plusieurs distributeurs croient même qu’il s’agit de la plus grosse activité de Paintball en Amérique du Nord&#160;».</p>
<ul>
<li>[Jungle] octobre 2007*</li>
</ul>
<p>Au Québec le mot Paintball a été soumis à l’office de la langue française par Denyse Létourneau de l’office et François Gagnon, entrepreneur et propriétaire du centre récréatif Bigfoot Paintball. Ce n’est qu’en 1996 qu’il fut adopté par l’office avec la définition suivante&#160;: Le terme «&#160;Paintball&#160;» a été préféré à d'autres propositions qui faisaient référence à la guerre, telles que «&#160;jeu de guerre&#160;», «&#160;guerre à la peinture&#160;». Le terme «&#160;jeu d'aventure&#160;» est considéré comme un terme trop générique et ne convient pas. «&#160;Paintball&#160;» désigne, au sens premier, le projectile lancé (la balle de peinture) et, par extension de sens, le sport lui-même. Des expressions ont été créées à partir du terme «&#160;Paintball&#160;»&#160;: terrain de Paintball, joueur de Paintball, équipement de Paintball, équipe de Paintball, Paintball en intérieur. Le terme «&#160;Paintball&#160;» a été étudié par la Commission de terminologie de l'Office de la langue française qui juge opportun de maintenir l'usage du terme «&#160;Paintball&#160;» très implanté sur le plan international depuis plusieurs années et dont la diffusion est limitée. <span style="color:#0000FF">[Office de la langue française, 1996]</span></p>

<h2>Équipement</h2>
<div class="thumb tright">
<div class="thumbinner" style="width:222px;"><a href="/wiki/Fichier:Paintball_lanceur.jpg" class="image"><img alt="" src="//upload.wikimedia.org/wikipedia/commons/thumb/8/88/Paintball_lanceur.jpg/220px-Paintball_lanceur.jpg" width="220" height="165" class="thumbimage" /></a>
<div class="thumbcaption">
<div class="magnify"><a href="/wiki/Fichier:Paintball_lanceur.jpg" class="internal" title="Agrandir"><img src="//bits.wikimedia.org/skins-1.18/common/images/magnify-clip.png" width="15" height="11" alt="" /></a></div>
Lanceur de paintball.</div>
</div>
</div>
<div class="thumb tright">
<div class="thumbinner" style="width:222px;"><a href="/wiki/Fichier:Paintballs.jpg" class="image"><img alt="" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Paintballs.jpg/220px-Paintballs.jpg" width="220" height="293" class="thumbimage" /></a>
<div class="thumbcaption">

<div class="magnify"><a href="/wiki/Fichier:Paintballs.jpg" class="internal" title="Agrandir"><img src="//bits.wikimedia.org/skins-1.18/common/images/magnify-clip.png" width="15" height="11" alt="" /></a></div>
Billes usagées.</div>
</div>
</div>
<div class="thumb tright">
<div class="thumbinner" style="width:222px;"><a href="/wiki/Fichier:20080831_paintball_IMG_4331.jpg" class="image"><img alt="" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/0f/20080831_paintball_IMG_4331.jpg/220px-20080831_paintball_IMG_4331.jpg" width="220" height="147" class="thumbimage" /></a>
<div class="thumbcaption">
<div class="magnify"><a href="/wiki/Fichier:20080831_paintball_IMG_4331.jpg" class="internal" title="Agrandir"><img src="//bits.wikimedia.org/skins-1.18/common/images/magnify-clip.png" width="15" height="11" alt="" /></a></div>
Lanceur avec son chargeur (le canon est obstrué par un capuchon de tissu par mesure de sécurité).</div>
</div>
</div>
<ul>
<li><b>Masque</b>&#160;: élément obligatoire, il protège le visage du joueur des impacts occasionnés par les billes de peinture. En l'an 2000, 1200 lésions oculaires dues à des accidents de paintball ont été répertoriées aux États-Unis, aucune des victimes ne portait de masque. Le paintball reste néanmoins un des sports les moins risqués lorsqu'il est correctement encadré.</li>

<li><b>Lanceur</b> (ou marqueur)&#160;: élément mécanique ou électronique servant à propulser les billes grâce au gaz (<a href="/wiki/Dioxyde_de_carbone" title="Dioxyde de carbone">CO<sub>2</sub></a> ou à l' air comprimé selon le système utilisé) contenu dans une bouteille. La limite légale américaine pour leur puissance est de 300 fps (300 pieds par seconde ou environ <span class="nowrap">100&#160;m/s</span>) en sortie de canon. En France les lanceurs sont des armes de 7<sup>e</sup> catégorie soumis a déclaration auprès de la préfecture à partir du moment où sa puissance est réglée au delà de 10 joules (soit environ 450fps). Dans ce cas un permis de chasse ou une licence de tir sportif accompagné d'un document officiel (cerfa) sont envoyés à la préfecture dont dépend l'acheteur. Cette démarche est effectuée par le vendeur. En dessous de 10 joules, une copie de la pièce d'identité ainsi que l'inscription de la vente dans un cahier de vente d'arme de 7<sup>e</sup> catégorie est obligatoire et suffit. Un lanceur électronique peut tirer en théorie jusqu'à 30 billes par seconde.

<ul>
<li><b><i>Les Stock Class</i></b> &#160;: ces marqueurs possèdent une réserve très limitée en billes et en gaz. Ils embarquent en général une dizaine de billes et utilisent des <i>sparklets</i> de gaz (Capsules de CO<sub>2</sub>). Lanceur à une main, ils ressemblent aux armes de poing que tout le monde connaît.</li>
<li><b><i>Les Lanceurs Pompes</i></b> &#160;: le réarmement est manuel et se fait grâce à deux pièces qui coulissent l'une sur l'autre permettant d'engager la bille dans le canon et d'armer le marteau destiné à relâcher l'air.</li>
<li><b><i>Les lanceurs semi-automatiques</i></b> &#160;: le réarmement est automatique mais l'éjection de la bille n'est pas continue si on garde la détente appuyée. Les lanceurs semi-automatiques sont aujourd'hui les plus utilisés dans le monde du paintball. On distingue cependant deux grandes familles&#160;:

<ol>
<li>Les Semi-auto Mécaniques&#160;: appelés "Méca". Sur ces lanceurs, l'action d'appuyer sur la détente relâche un marteau qui libère à l'impact et pendant un court instant le gaz comprimé de la bouteille permettant d'éjecter la bille.</li>
<li>Les Semi-auto Electroniques&#160;: généralement dédiés au paintball sportif, ils embarquent une carte électronique programmable et un ensemble de capteurs (le plus courant étant un œil laser pour certifier la présence d'une bille) permettant d'augmenter considérablement le débit des tirs et de réduire la casse de bille. L'action d'appuyer sur la détente vient activer un interrupteur relié à la carte électronique logée dans la poignée du lanceur (de manière générale, certains modèles ont des cartes situées en d'autres éléments). La carte active ensuite une électrovanne qui libère l'air pour expulser la bille. Les cartes proposent en général certains modes de tir assistés (ou Ramping). Grâce à ces modes, le nombre de billes lancées est supérieur au nombre de pressions sur la détente. Selon les tournois, certains "modes" pourront être autorisés ou non. Ils sont en général réglementés par le nombre de billes par seconde (limité à douze pour la majorité des tournois) et par le temps séparant deux billes. Ces lanceurs demandent un réglage et un entretien minutieux pour un fonctionnement optimal.</li>
</ol>
</li>
<li><b><i>Les lanceurs automatiques</i></b> &#160;: Ils sont considérés comme armes de 4<sup>e</sup> catégorie en France et sont donc interdits sur la plupart des terrains de loisirs et tous les terrains de compétition. Ce sont des lanceurs électroniques semi-automatiques débridés (ou importés des USA par exemple) afin de tirer tant que l'appui est maintenu sur la gachette.</li>
</ul>

</li>
<li><b>Bouchon de canon</b>&#160;: Élément essentiel de la sécurité dans le paintball, le bouchon de canon est une pièce servant à obstruer la sortie de canon de façon suffisamment résistante qu'un tir accidentel de bille soit stoppé. Les bouchons en plastique (<i>barrel plug</i>) à joints ont tendance à disparaître au profit de sacs à canon ou <i>barrel sock</i> qui sont des poches en tissu résistant maintenues sur le canon par des élastiques puissants reliés à l'arrière du marqueur. Cet élément est obligatoire sur tous les terrains de paintball et tous les lanceurs sont vendus avec.</li>
<li><b>Verrou de pontet</b>&#160;: Système de verrouillage à clé qui permet de bloquer l'accès à la détente du lanceur, le verrou vient se loger sur l'arcade de pontet empêchant tout mouvement de la queue de détente et donc tout tir accidentel. Cela ressemble à un cadenas ovale. Bien que le bouchon de canon est largement plus utilisé du fait de son prix et de sa disponibilité aisée, le verrou de pontet est l'un des moyens de sécurité le plus sûr, car il empêche qui que ce soit d'autre que le propriétaire de tirer avec le lanceur.</li>
<li><b>Billes</b>&#160;: Les billes sont pour un joueur régulier l'équipement le plus coûteux. Il s'agit de deux coques de gélatine (souvent de l'amidon) solides, remplies de colorant alimentaire et soudées l'une à l'autre. La composition du mélange interne est polyéthylène glycol, sorbitol, glycérine et eau dans la majorité des cas, mélange à fort pouvoir osmotique, ce qui peut entrainer en cas d'ingestion une diarrhée. Elles doivent être biodégradables et non-toxiques. On en trouve de plus ou moins tachantes et à la fragilité variable pour jouer en diverses saisons. Les billes peuvent être de n'importe quelle couleur, en général se sont des couleurs fluo pour repérer le marquage plus facilement, il en existe même des pailletées. Certain joueurs de scenario utilisent le rouge, mais cette couleur est rarement utilisé par les autres joueurs qui la jugent trop sanglante. Leur dégradabilité est variable, de quelques jours à plusieurs mois. La qualité d'une bille est définie par la régularité de sa coquille, de la soudure, son pouvoir tachant, sa résistance (évitant qu'elle casse dans le lanceur) et sa fragilité (favorisant la casse à l'impact). Les meilleures billes sont encore fabriquées sur le continent américain.</li>

<li><b>Loader</b>&#160;: Chargeur, réservoir de billes. Afin de pouvoir suivre la cadence de tir des lanceurs électroniques, certains <i>loaders</i> sont équipés d'une hélice mécanique actionnée par un moteur électrique alimenté par des piles, et qui agit comme une sorte de turbine qui accroît le débit de billes. Ces <i>loaders</i> sont également électroniques, puisqu'une carte permet de régler leur vitesse. Certains <i>loaders</i> possèdent un "œil" optique (détecteur de bille) ou capteur sonore afin de ne pas fonctionner continuellement.</li>
<li><b>Gaz</b>&#160;: Le gaz de propulsion de la bille est soit du CO<sub>2</sub> soit de l'air comprimé (couramment appelé "nitro", puisque l'air est composé en majeure partie d'azote). Le CO<sub>2</sub> est un gaz qui coûte peu cher à l'achat, mais a tendance à geler quand on le détend trop vite (tirs rapides). De plus c'est un gaz qui réagit énormément aux différences de température ce qui occasionne des variations importantes de pression, et par conséquent, une vitesse de bille approximative. Le CO<sub>2</sub> est plus agressif que l'air sur les joints et la mécanique interne du lanceur&#160;; on l'utilise principalement pour les lanceurs de loisir ou semi-auto mécaniques. L'air comprimé est beaucoup plus stable aux variations de température, il ne gèle pas, a des débits soutenus et est donc indispensable pour alimenter les lanceurs électroniques.</li>

<li><b>Bouteilles</b>&#160;: Les bouteilles sont des réservoirs de gaz en aluminium, fibre de verre ou kevlar permettant de concilier légèreté et résistance à la pression. Leur pression est donnée en psi (<i>pounds per square inch</i>, livres-force par poucecarré&#160;: 1 psi ≈ 0,068 94 bar). Les pressions dans les bouteilles d'air peuvent atteindre 4500 psi (presque 320 bars) pour une contenance d'environ 1 L. Elles se rechargent sur des bouteilles d'air de plongée (appelées bouteilles tampons) équipées de connexions spéciales ou sur des compresseurs fixes ou mobiles de plus grande capacité.</li>
<li><b>Les régulateurs</b>&#160;: Ils sont collés sur la bouteille d'air et se vissent au lanceur. Ils permettent de réduire la pression en sortie de bouteille. On distingue les régulateurs basse pression (B.P. 425 psi environ) et haute pression (H.P. 850 psi environ). Un régulateur basse pression permet de réduire le choc lors du remplissage du régulateur interne du lanceur. Selon certains, il permettrait aussi de pousser plus longtemps la bille dans le canon, améliorant la trajectoire de celle-ci.</li>
</ul>
<p>Sans oublier, bien sûr, les diverses protections, tels que genouillères, coudières, shorts rembourrés, gants, vêtements de protection ou de style camouflage militaire&#160;; à ce sujet une controverse existe dans le milieu du paintball, car les tenues de camouflage militaire donneraient selon certains une image militariste à ce loisir de détente. Néanmoins, malgré toutes les considérations sujettes à polémiques, les tenues camouflantes sont, sur certains terrains dotés d'une végétation dense, très efficaces pour se dissimuler de la vue des adversaires mais rarement utilisées sur les terrains de compétition.</p>

<p>Bien qu’il semble y avoir une certaine polémique au sujet de la simulation militaire au Paintball, la situation semble être très différente et cela dépendrait de la situation géographique/politique où le sport est pratiqué. De toute évidence, il semblerait que ce soit un sujet plus sensible dans les pays où les traces de la guerre sont encore bien visibles, tandis qu’au Canada par exemple, malgré la militarisation du jeu, les gens considèrent le sport comme une activité sportive récréative en famille, entre amis ou copains de bureau. Au fil des ans il y a même de plus en plus de filles qui s’adonnent à ce sport puisqu’il s’agit d’une activité que les jeunes et les moins jeunes peuvent pratiquer.</p>
<p>«&#160;En Allemagne, la simulation était mal vue, tandis que l’Angleterre fut un des premiers pays européens à adopter ce style de jeu. En France , le Paintball avait une connotation militaire&#160;; jouer au Paintball c’était comme faire la guerre. C’est pourquoi la France a inventé le speedball avec les obstacles gonflables&#160;».</p>
<ul>
<li>Romain Manière, journaliste spécialisé, canal D épisode&#160;: <i>Comme à la guerre</i> janvier 2011</li>

</ul>
<p>Il y aura toujours un débat sur la violence dans le sport, c’est certain que la version militarisée du Paintball avec ses uniformes militaires, ses tactiques, des répliques d’armes de plus en plus réelles, des scénarios basés sur les films de guerre ou sur des missions historiques amène à y penser et pourtant certains spécialistes se sont penchés sur le sujet et voici ce qu’ils en pensent&#160;: «&#160;Ce que les gens veulent voir, c’est de mettre en scène des répliques de jeu de la guerre moderne… la simulation d’une réalité, d’une réalité virtuelle…on n’a jamais réglé le cas du guerrier en nous, du fait que la guerre est une réalité, le mâle humain est constitué, fabriqué, fait pour la brutalité, l’action, la violence. C’est très correct d’envoyer des gens jouer, ils ne font pas de mal à personne. Nous sommes une société de consommation de loisirs, le Paintball est un dérapage fantasmatique; vous voulez avoir la sensation d’un corps d’Élite dans le bois, dans un entrepôt.&#160;»</p>
<p>«&#160;Le Paintball ne reproduit pas l’armée canadienne ou l’armée américaine. Il reproduit ce qu’on pense de la guerre, il reproduit Hollywood les films d’action que l’on voit, une fiction, la simulation d’une reproduction. Nous sommes très loin de la réalité; la réalité n’intéresse plus personne!&#160;» «&#160;Les jeux qui représentent la guerre 39/45 en Europe ne seraient pas populaires dans les pays où la guerre est en cours ou dans les pays qui ont souffert. Là il y a une aversion pour l’uniforme, les armes, la violence. Tant que c’est frais dans la mémoire cela reste un sujet tabou. Dans une société loin de cela ça fait partie des jeux possibles. Le jeu va être de plus en plus intense si tu es éloigné de cette réalité».</p>
<p>Serge Bouchard, anthropologue, canal D épisode <i>Comme à la guerre</i> janvier 2011</p>

<h2><span class="editsection">[<a href="/w/index.php?title=Paintball&amp;action=edit&amp;section=3" title="Modifier la section : Terrains">modifier</a>]</span> <span class="mw-headline" id="Terrains">Terrains</span></h2>
<div class="thumb tright">
<div class="thumbinner" style="width:252px;"><a href="/wiki/Fichier:Paintball_indoor.jpg" class="image"><img alt="" src="//upload.wikimedia.org/wikipedia/fr/thumb/d/d7/Paintball_indoor.jpg/250px-Paintball_indoor.jpg" width="250" height="188" class="thumbimage" /></a>
<div class="thumbcaption">
<div class="magnify"><a href="/wiki/Fichier:Paintball_indoor.jpg" class="internal" title="Agrandir"><img src="//bits.wikimedia.org/skins-1.18/common/images/magnify-clip.png" width="15" height="11" alt="" /></a></div>
Aire de jeu de la compétition de paintball en salle Euroball III de novembre 2003</div>
</div>
</div>
<div class="thumb tleft">
<div class="thumbinner" style="width:252px;"><a href="/wiki/Fichier:Paintball_3.jpg" class="image"><img alt="" src="//upload.wikimedia.org/wikipedia/commons/thumb/6/64/Paintball_3.jpg/250px-Paintball_3.jpg" width="250" height="123" class="thumbimage" /></a>
<div class="thumbcaption">

<div class="magnify"><a href="/wiki/Fichier:Paintball_3.jpg" class="internal" title="Agrandir"><img src="//bits.wikimedia.org/skins-1.18/common/images/magnify-clip.png" width="15" height="11" alt="" /></a></div>
vue générale d'un terrain de paintball</div>
</div>
</div>
<p>La <a href="/wiki/For%C3%AAt" title="Forêt">forêt</a> ou les sites naturels, ont été historiquement les premières catégories de terrains utilisées, les arbres et la végétation faisant office d'obstacles naturels. Le paintball a été souvent pratiqué de manière "sauvage" dans des bâtiments industriels désaffectés, mais les pratiques actuelles de sécurité et d'assurance n'encouragent pas ce genre de pratiques marginales et souvent réprimandées par la loi faute d'encadrement approprié. Dans un second temps, le jeu s'est développé sur des terrains en plaine garnis d'obstacles artificiels permettant aux spectateurs une vision de l'ensemble du jeu. Des parcours en salle sur le même principe existent également. Enfin se sont développés dernièrement des obstacles gonflables pouvant être installés sur n'importe quel type de terrain sportif et offrant une très bonne visibilité aux spectateurs, ils sont rapidement devenus la norme pour les compétitions.</p>
<p>Le paintball est possible dans la plupart des pays, mais, par exemple, l'<a href="/wiki/Italie" title="Italie">Italie</a>, le <a href="/wiki/Luxembourg_(pays)" title="Luxembourg (pays)">Luxembourg</a> et certains <a href="/wiki/L%C3%A4nder_allemands" title="Länder allemands" class="mw-redirect">Länder allemands</a> en interdisent la pratique. En <a href="/wiki/France" title="France">France</a>, il n'est pas possible de jouer sur un terrain du <a href="/wiki/Domaine_public" title="Domaine public">domaine public</a>, mais il existe de nombreux clubs ou sociétés privées louant des terrains adaptés à cette activité et répondant à la législation en vigueur. Il n'existe pas d'interdiction <i>a priori</i> pour organiser une partie sur un terrain privé, mais, comme pour toute activité de ce type, la responsabilité de l'organisateur peut être engagée en cas de problèmes. Par ailleurs, des billes bien que parfaitement <a href="/wiki/Biod%C3%A9gradables" title="Biodégradables" class="mw-redirect">biodégradables</a> mettent plusieurs semaines à disparaître et certaines surfaces perméables, comme le crépi des maisons, peuvent être tachées durablement.</p>

<h2><span class="editsection">[<a href="/w/index.php?title=Paintball&amp;action=edit&amp;section=4" title="Modifier la section : Le paintball sportif">modifier</a>]</span> <span class="mw-headline" id="Le_paintball_sportif">Le paintball sportif</span></h2>
<div class="thumb tright">
<div class="thumbinner" style="width:352px;"><a href="/wiki/Fichier:Paintball_terrain.jpg" class="image"><img alt="" src="//upload.wikimedia.org/wikipedia/fr/thumb/d/db/Paintball_terrain.jpg/350px-Paintball_terrain.jpg" width="350" height="156" class="thumbimage" /></a>
<div class="thumbcaption">
<div class="magnify"><a href="/wiki/Fichier:Paintball_terrain.jpg" class="internal" title="Agrandir"><img src="//bits.wikimedia.org/skins-1.18/common/images/magnify-clip.png" width="15" height="11" alt="" /></a></div>
Vue aérienne des terrains du MAXS European Masters 2004</div>
</div>
</div>
<p>Le paintball sportif représente la version ancienne et adaptée à la compétition de loisir du même nom. Il peut être au choix classé dans la catégorie des sports extrêmes (par les sensations qu'il procure) ou dans les sports mécaniques (à cause des lanceurs utilisés par les joueurs pour envoyer les billes).</p>
<p>Un travail important a été fait pour débarrasser le paintball sportif de sa connotation militaire, les tenues de camouflage et les billes de couleur rouge sont par exemple interdites en compétition en France. Le paintball sportif se distingue également par l'utilisation d'un terrain normalisé symétrique permettant aux spectateurs de suivre les parties en toute sécurité.</p>

<p>En compétition, les terrains sont constitués d'obstacles artificiels (gonflables le plus souvent) organisés de manière symétrique et qui doivent être complètement entourés de filets de <span class="nowrap">6&#160;mètres</span> de haut afin d'éviter les projections de billes sur les spectateurs.</p>
<p>Malgré l'appellation paintball sportif, cette activité est considérée en France comme une «&#160;activité physique de loisir&#160;» et non un sport, par le ministère chargé des Sports. Les fédérations de paintball sportif européennes sont regroupées sous l'entité EPBF (European PaintBall Federation) qui gère un système de licence commun aux circuits privés et associatifs. Cette même EPBF est sous l'égide de l'UPBF (United Paintball Federation) regroupant les fédérations américaines et asiatiques. Il n'y a néanmoins pas encore de vrai circuit mondial organisé.</p>
<h3><span class="editsection">[<a href="/w/index.php?title=Paintball&amp;action=edit&amp;section=5" title="Modifier la section : Composition d'une équipe">modifier</a>]</span> <span class="mw-headline" id="Composition_d.27une_.C3.A9quipe">Composition d'une équipe</span></h3>
<p>Au paintball sportif, on distingue plusieurs postes aux rôles bien définis&#160;:</p>

<ul>
<li><b>Les couvreurs</b>&#160;: Joueurs de fond de terrain, ils sont généralement les plus expérimentés. En charge de la couverture des avants, ils se doivent de délivrer un grand volume de billes pour permettre à un équipier de rentrer profondément dans la surface adverse. Il est également le dernier rempart avant le drapeau. Une des techniques défensives de base consiste à faire "croiser" les couvreurs, afin d'éviter toute avancée adverse, chaque couvreur positionné d'un côté du terrain "croise" en bloquant les avancées du côté intérieur du terrain de son angle de vision, cela permet de verrouiller un terrain avec seulement deux couvreurs.</li>
</ul>
<ul>
<li><b>Les avants</b>&#160;: Ils sont là pour prendre les positions les plus avancées dans la surface adverse et attirer les tirs ou surprendre les adversaires selon les stratégies adoptées. Vivacité, rapidité et précision sont les principales caractéristiques des avants, leur place est risquée mais une action payante donne de grandes chances de remporter le match. C'est ainsi souvent la position des joueurs stars, car l'audace et les prises de risques spectaculaires font partie du jeu de l'avant.</li>
</ul>
<ul>
<li><b>Le milieu</b>&#160;: Joueur qui va orienter le jeu, appuyer les avants ou prendre l'initiative, le milieu est l'élément polyvalent de l'équipe. En joueur expérimenté, défensif ou offensif, il prendra la place d'un équipier éliminé ou assurera la deuxième vague d'une attaque. C'est aussi en dehors des parties de format long l'élément essentiel de communication, assurant la liaison entre le côté droit et le côté gauche du terrain, il est donc primordial de posséder dans son équipe un joueur de milieu de terrain ayant une bonne vue du jeu et la tête sur les épaules afin d'organiser correctement le déroulement de la partie. C'est souvent la position du Capitaine de l'équipe.</li>
</ul>
<p>Le format long nécessite de nouveaux éléments dans l'équipe de paintball typique&#160;:</p>

<ul>
<li><b>Le Coaching</b>&#160;: Le format long contrairement aux formats dits classiques permet à des personnes extérieures à l'aire de jeu de communiquer avec les joueurs sur les terrains, mais dans une zone limitée, avec des personnes définies. Les "coaches" sont des personnes travaillant à l'avancée des joueurs à portée de leur voix, indiquant des informations essentielles à la progression du jeu, au format long de type Millennium, un coach est autorisé de chaque côté du terrain, derrière les filets de protection, ils ont aussi la possibilité d'utiliser un porte voix non-électronique ainsi que des panneaux indicateurs. Cet élément récent dans le paintball apporte une manière de jouer totalement différente où non seulement la technique pure est mise en valeur, mais où la compétence et les qualités d'un coach peuvent être décisifs sur un tournoi.</li>
</ul>
<ul>
<li><b>Le pit crew</b>&#160;: ou mot à mot "équipe du stand", comme en formule 1, il s'agit essentiellement de personnes de support technique, veillant à ce qu'entre chaque point de format long chaque élément du joueur soit prêt à repartir&#160;; nettoyage en cas d'impact, remplissage d'air, remplissage de billes, nourriture et boisson. En Millennium, deux "Pit crew" sont autorisés par équipe.</li>
</ul>
<h3><span class="editsection">[<a href="/w/index.php?title=Paintball&amp;action=edit&amp;section=6" title="Modifier la section : Compétition en France">modifier</a>]</span> <span class="mw-headline" id="Comp.C3.A9tition_en_France">Compétition en France</span></h3>

<p>La <a href="/wiki/F%C3%A9d%C3%A9ration_de_Paintball_Sportif" title="Fédération de Paintball Sportif" class="mw-redirect">Fédération de Paintball Sportif</a> s'occupe de la gestion des compétitions fédérales via des ligues régionales. Chaque ligue est autonome au niveau de la gestion de son championnat régional, et les saisons sont établies sur un calendrier scolaire (septembre à juin). À la fin de chaque saison est organisé un championnat national (aussi appelé championnat de la Fédération) regroupant les meilleures équipes de chaque format à <a href="/wiki/Vichy" title="Vichy">Vichy</a> sur un site dédié de 2001 à 2007, depuis 2008 il est itinérant. Pour participer à la Fédération et afin d'aider à l'obtention d'une délégation de l'état au ministère de la santé et du sport afin de devenir Fédération Nationale, les clubs doivent être structurés sous forme d'associations dont les adhérents acquièrent une licence fédérale de compétition. Ils peuvent alors participer au circuit de ligue, ou de loisir si l'on souhaite simplement pratiquer le paintball sur un terrain affilié<sup id="cite_ref-2" class="reference"><a href="#cite_note-2"><span class="cite_crochet">[</span>3<span class="cite_crochet">]</span></a></sup>. Plus d'informations sur le site officiel de <a rel="nofollow" class="external text" href="http://www.paintball-france.com/index.php">la FPS</a>.</p>
<p>La <a href="/wiki/F%C3%A9d%C3%A9ration_de_Paintball_Sportif" title="Fédération de Paintball Sportif" class="mw-redirect">Fédération de Paintball Sportif</a> a regagné beaucoup de crédibilité en fédérants les plus importantes équipes Françaises durant ces deux dernières années. Pour rassembler à nouveau grandes et petites équipes, depuis 2007 est organisé l'<b>Open De France</b>, une rencontre ouverte aux équipes affiliées et non affiliées françaises sur le site du Championnat National, et le réglement français est dorénavant harmonisé avec celui du circuit européen.</p>

<p>En France seuls six formats de jeu sont reconnus par la FPS&#160;:</p>
<ul>
<li>la <b>Fun Cup</b>&#160;: Ce format est exclusivement français et uniquement pratiqué dans le cadre de la FPS, il n'y a pas de tournois privés ou de circuit autre que les ligues régionales en Fun Cup. Parti sur un principe de «&#160;format économique&#160;», car limité en nombre de billes par joueur (140), il oppose 5 joueurs plus un 6<sup>e</sup> s'il est équipé d'un lanceur stock class. Bien que prévu pour lancer les joueurs débutants dans la compétition, le format n'attire que des aficionados et reste marginal, bien que relativement plus populaire que le format Pompe&#160;;</li>
</ul>
<ul>
<li>le <b>pompe</b>&#160;: chaque équipe est composée de 5 joueurs avec des marqueurs à pompe sans limitation du nombre de billes. La catégorie Pompe est la seule à bénéficier d'un circuit national en plus du circuit régional classique, il s'agit de la Coupe Nationale Pompe. Depuis la saison 2006-2007, elle est aussi la seule catégorie à avoir un championnat national séparé des autres, à <a href="/wiki/Moli%C3%A8res" title="Molières">Molières</a> en 2007 et à [[]] en 2008. Cette catégorie qui fut historiquement "l'école du paintball" est sur le déclin depuis quelques saisons et ne survit que grâce à la CNP, dans le but de redynamiser le jeu le format long type CPL Millennium (voir plus bas) a été adopté&#160;;</li>

</ul>
<ul>
<li>le <b>semi 3</b>&#160;: chaque équipe est composée de 3 joueurs (+1 remplaçant max) avec des marqueurs semi-automatiques sans limitation du nombre de billes, le jeu est basé sur une capture de drapeau dans la base adverse que l'on doit ramener dans sa propre base sans avoir été touché, la durée de jeu est de 3 minutes&#160;;</li>
<li>le <b>semi 3 Format Long</b>&#160;: Ce format est le même que le semi 3 sauf qu'un match est composé de plusieurs points et celui qui gagne est le premier à avoir marqué 4 points&#160;;</li>
<li>le <b>semi 5</b>&#160;: chaque équipe est composée de 5 joueurs (+2 remplaçants max) avec des marqueurs semi-automatiques sans limitation du nombre de billes, même règles de drapeau, durée de jeu de 5 minutes&#160;;</li>

<li>le <b>semi 5 Format Long</b>&#160;: Inspiré du format SPL du Millennium, lui-même inspiré du format X-Ball américain. Le format long a été mis en place pour la saison 2007-2008 (voir format SPL pour le système de jeu)&#160;;</li>
<li>le <b>semi 7</b>&#160;: chaque équipe est composée de 7 joueurs (+3 remplaçants max) avec des marqueurs semi-automatiques sans limitation du nombre de billes, même règles de drapeau, durée de jeu de 7 minutes&#160;; Ce format n'est plus pratiqué en ligue depuis 2008.</li>
</ul>